server:
  port: 7999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: snp-api-gateway

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: snp-css
#          uri: lb://snp-web/css/
#          predicates:
#            - Path=/css/**
#        - id: snp-js
#          uri: lb://snp-web/js/
#          predicates:
#            - Path=/js/**
#        - id: snp-img
#          uri: lb://snp-web/img/
#          predicates:
#            - Path=/img/**
#        - id: snp-assets-img
#          uri: lb://snp-web/assets/img/
#          predicates:
#            - Path=/img/**
#        - id: snp-font
#          uri: lb://snp-web/font/
#          predicates:
#            - Path=/font/**
#        - id: snp-fonts
#          uri: lb://snp-web/fonts/
#          predicates:
#            - Path=/font/**
#        - id: snp-data
#          uri: lb://snp-web/data/
#          predicates:
#            - Path=/data/**
#        - id: snp-assets-data
#          uri: lb://snp-web/assets/data/
#          predicates:
#            - Path=/data/**
#        - id: snp-main-service
#          uri: lb://snp-web
#          predicates:
#            - Path=/main/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true


