server:
  port: 7999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: snp-css
          uri: http://localhost:8001/css/
          predicates:
            - Path=/css/**
        - id: snp-js
          uri: http://localhost:8001/js/
          predicates:
            - Path=/js/**
        - id: snp-img
          uri: http://localhost:8001/img/
          predicates:
            - Path=/img/**
        - id: snp-assets-img
          uri: http://localhost:8001/assets/img/
          predicates:
            - Path=/img/**
        - id: snp-font
          uri: http://localhost:8001/font/
          predicates:
            - Path=/font/**
        - id: snp-fonts
          uri: http://localhost:8001/fonts/
          predicates:
            - Path=/font/**
        - id: snp-data
          uri: http://localhost:8001/data/
          predicates:
            - Path=/data/**
        - id: snp-assets-data
          uri: http://localhost:8001/assets/data
          predicates:
            - Path=/data/**
        - id: snp-main-service
          uri: http://localhost:8001
          predicates:
            - Path=/main/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
